name: TLA+ Verification

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  verify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Download TLA+ CLI
        run: |
          wget https://github.com/tlaplus/tlaplus/releases/download/v1.7.4/tla2tools.jar -O tla2tools.jar

      - - name: Run TLC Model Checker
  run: |
    echo "Running TLC on MCVotor.tla with MCVotor.cfg"
    tlc MCVotor.tla -config MCVotor.cfg


      - name: Run TLC on Rotor spec
        continue-on-error: true
        run: |
          echo "Running TLC on rotor.tla with rotor.cfg"
          java -cp tla2tools.jar tlc2.TLC tla/rotor/rotor.tla -config tla/rotor/rotor.cfg
