name: TLA+ Verification

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  verify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Download TLA+ Toolbox
  run: |
    wget https://github.com/tlaplus/tlaplus/releases/download/v2.17.0/tlaplus-2.17.0-linux-x86_64.tar.gz
    tar -xzf tlaplus-2.17.0-linux-x86_64.tar.gz
    sudo mv tlaplus-2.17.0-linux-x86_64 /opt/tlaplus

